[package]
name = "predicatefunction/greedy-mesher"
description = "A greedy meshing library"
version = "0.1.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
author = "PredicateFunction"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json"]